name: Update dependencies
on:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  update:
    uses: particular/dependency-updates-action/.github/workflows/run-dependency-updates.yml@main
    secrets: inherit
