name: Update dependencies
on:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  update:
    uses: particular/version-monkey-action/.github/workflows/run-version-monkey.yml@main
    secrets: inherit